11.0 mig l10n it ddt
SimoRubi/l10n-italy pull request #1
Opened 2018-09-08 00:09 UTC by SilvioGregorini

@SimoRubi here is my PR with all the work I've done so far.
I think the last two commits may be merged or squashed into a single one, yet I wasn't sure about it... so I left them as they were.

2018-09-10 16:23 UTC, SimoRubi requested changes
Hi, thanks for your work.
Before adding new functionalities, I'd prefer to be sure that the migration commit works correctly so please keep the other 4 commits in another branch and let's work only on the migration.
You will be able to do another PR for your new functionalities directly in https://github.com/OCA/l10n-italy when the module is up and running in v11.

Moreover, I suggest not to comment the old things but directly remove them, they only confuse the reader.

In order to check if the module migrated to v11 works, we first have to migrate its dependencies, so please have a look at https://github.com/OCA/stock-logistics-workflow/pull/448

2018-09-10 16:23 UTC, SimoRubi commented on l10n_it_ddt/models/stock_picking_package_preparation.py
> +    # def quantity_by_lot(self):
Either keep the method, or delete it

2018-09-10 16:23 UTC, SimoRubi commented on l10n_it_ddt/wizard/add_picking_to_ddt.xml
> +    <!--
Either keep the record, or delete it

2018-09-12 10:55 UTC, SilvioGregorini commented
Hi @SimoRubi, I'm splitting the branch right now.
I'm creating two new branches (one for the migration only, the other one for new features to be implemented). They should be ready this afternoon.

2018-09-12 10:57 UTC, SimoRubi commented
Thanks, and please remember to have a look at https://github.com/OCA/
stock-logistics-workflow/pull/448 when you have time, otherwise we can't
complete the migration of l10n_it_ddt

On 12 September 2018 at 12:55, SilvioGregorini <notifications@github.com>
wrote:

> Hi @SimoRubi <https://github.com/SimoRubi>, I'm splitting the branch
> right now.
> I'm creating two new branches (one for the migration only, the other one
> for new features to be implemented). They should be ready this afternoon.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/SimoRubi/l10n-italy/pull/1#issuecomment-420605458>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AelFHD8l5WDP6pHufatQFSk2OoWkomQCks5uaOgLgaJpZM4WfoI4>
> .
>

2018-09-12 14:43 UTC, SilvioGregorini commented
@SimoRubi I think you might wanna cancel this PR.
PR #2 suffices for the migration commit, while the other commits will be left in my own branch while I develop them.

2018-09-12 14:47 UTC, SimoRubi commented
Superseded by #2

2018-09-12 14:47 UTC, closed without merging