12.0 l10n it fatturapa binding diff
SimoRubi/l10n-italy pull request #11
Opened 2020-06-11 14:18 UTC by sergiocorato

2020-06-11 15:36 UTC, SimoRubi requested changes

2020-06-11 15:36 UTC, SimoRubi commented on l10n_it_fatturapa/bindings/binding.py
> +<<<<<<< HEAD
Questi conflitti sono da risolvere

2020-06-11 15:47 UTC, sergiocorato commented on l10n_it_fatturapa/bindings/binding.py
> +<<<<<<< HEAD
si ho fatto un po' di casino

2020-06-11 15:52 UTC, sergiocorato commented on l10n_it_fatturapa/bindings/binding.py
> +<<<<<<< HEAD
ho ripulito

2020-06-12 07:46 UTC, SimoRubi approved these changes

2020-06-12 07:47 UTC, merged